# Site settings
title: Writing Penguin
email: thewritingpenguin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Offical website of J.S. Grant
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://writingpenguin.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
timezone: America/New_York
gems: [jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
